name: Build Dorsh on Windows

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/**'
      - 'Make/VSCode/build.bat'
      - 'Make/**Makefile'
      - 'Make/**Marefile'
      - 'Make/**.mare'
      - 'Util/GameController/include/**'
      - 'Src/Utils/dorsh/**'
      - 'Src/Tools/**'
      - 'Src/Platform/**'

jobs:
  build_simrobot:
    name: Dorsh
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: generate
      working-directory: ./Make/VS2019/
      run: ..\..\Util\SimRobot\Util\mare\Windows\bin\mare.exe --vcxproj=2019 ssse3=true avx2=true
    - name: make
      shell: cmd
      run: Make\VSCode\build.bat Make\VS2019\NDevils.sln Develop Utils\dorsh
    # - uses: actions/upload-artifact@v1
      # with:
        # name: binary
        # path: Build/Windows/dorsh/Develop
