name: Build Dorsh on Linux

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/**'
      - 'Make/**Makefile'
      - 'Make/**Marefile'
      - 'Make/**.mare'
      - 'Util/GameController/include/**'
      - 'Src/Utils/dorsh/**'
      - 'Src/Tools/**'
      - 'Src/Platform/**'

jobs:
  build_simrobot:
    name: Dorsh
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: sudo apt update && sudo apt install libqt4-dev libqt4-dev-bin qt4-dev-tools libjpeg-dev
    - name: make
      working-directory: ./Make/Linux/
      run: make dorsh
    # - uses: actions/upload-artifact@v1
      # with:
        # name: binary
        # path: Build/Linux/dorsh/Develop
