name: Formatting

on:
  pull_request:

jobs:
  clang_format:
    name: ClangFormat
    runs-on: Linux
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: '0'
    - name: Check C++ formatting
      run: .github/workflows/clang-format.sh $GITHUB_BASE_REF
  line_endings:
    name: Line endings
    runs-on: Linux
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'
    - name: Check line endings
      run: .github/workflows/line-endings.sh $GITHUB_BASE_REF
