name: Build and test on Linux

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'Config/**'
      - '!Config/Robots/**'
      - 'Config/Robots/Nao/**'
      - '!Config/Overlays/**'
      - 'Make/CMake/**'
      - 'Make/Linux/test.sh'
      - 'Src/**'
      - 'Util/**'

jobs:
  build_simrobot:
    name: Build framework
    runs-on: Linux
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: Make/Linux/compile.sh
    - name: test
      run: Make/Linux/test.sh
