name: Build robot

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'Make/CMake/**'
      - 'Src/**'
      - 'Util/**'
      - '!Src/Utils/dorsh/**'

jobs:
  build_nao:
    name: Build framework
    runs-on: Linux
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: compile
      run: Make/Linux/compile.sh nao-develop
